# Generated by Django 4.0.3 on 2022-05-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_item_quantity_remove_item_size_cart_item_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Shirts', 'Shirts'), ('Skirts', 'Skirts'), ('Pants', 'Pants'), ('Dresses', 'Dresses'), ('Jackets', 'Jackets')], max_length=20, null=True),
        ),
    ]
